### ISSUE TITLE
LDA Example missing link to dataset

### ISSUE THREAD

**Issue by mihaivavram** [DSC-SPIDAL/harp#40]
In the LDA application: https://dsc-spidal.github.io/harp/docs/applications/lda-cgs/

The [dataset ](https://github.iu.edu/IU-Big-Data-Lab/ml-bench/blob/master/dataset/dataset-mf.md) at the bottom of the page is missing a link

**Comment by kyhhdm** [comment]
commit bd4598f4ab243a687239a4afb1808aa54cc8d5b7
fix issue: LDA Example missing link to dataset #40
